version: '3.8'
services:
  frontend:
    build:
      context: ./file-manager-fe
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./file-manager-be
    ports:
      - "5000:5000"
